### ISSUE TITLE
Which file should I run ?

### ISSUE THREAD

**Issue by ssw940521** [MeteorYee/LSTM-CNN-CWS#1]
Can you describe more details about the file's usage ? Thx

**Comment by MeteorYee** [comment]
My apology to you, I've just opened this repository and got no time to write an introduction. I am handling with the experiments about this model recently, and there still are some places needed to be fixed. Maybe I could finish this in the month. Sorry again...

**Comment by MeteorYee** [comment]
My apology to you, I've just opened this repository and got no time to write an introduction. I am handling with the experiments about this model recently, and there still are some places needed to be fixed. Maybe I could finish this in the month. Sorry again...
