### ISSUE TITLE
F=91% on pku dataset with default setting, anyway to enhanced to 95%?

### ISSUE THREAD

**Issue by SeekPoint** [MeteorYee/LSTM-CNN-CWS#6]

**Comment by MeteorYee** [comment]
Hi, sorry for the late reply. I think that's how it works. The data size of PKU is not big enough to get the system state-of-the-art. Moreover, this is not a cutting-edge architecture either right now. General tweaking techniques like hyperparameter search, stacking more LSTM layers and increasing the unit numbers might help, but I don't think it's gonna boost the F-value all the way to 95%. Thanks for trying out my code :)

**Comment by MeteorYee** [comment]
Just a follow-up. Maybe you can try pre-trained Chinese characters embeddings on large corpus like Wikipedia's dataset. Or is there a Chinese version BERT from which you can grab some pre-trained data? I think this is the most promising one.
